name: resize_observer
version: 1.0.1
description: A Dart wrapper for the ResizeObserver API (Dart 1 & 2 compatible)
author: Rob Becker <rob.becker@gmail.com>
homepage: https://github.com/robrbecker/resize_observer

environment:
  sdk: '>=1.22.1 <3.0.0'

dev_dependencies:
  build_runner:
  build_web_compilers:
