name: resize_observer
version: 1.1.0
description: A Dart wrapper for the ResizeObserver API that uses JS interop and a single observer
homepage: https://github.com/robrbecker/resize_observer

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic:
  build_runner:
  build_web_compilers:
