name: resize_observer
version: 1.1.0-nullsafety.0
description: A Dart wrapper for the ResizeObserver API (Dart 1 & 2 compatible)
homepage: https://github.com/robrbecker/resize_observer

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  build_runner:
  build_web_compilers:
